// USER ACTION TYPES //
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// FETCH BOOKINGS //
export const FETCH_BOOKINGS_REQUEST = 'FETCH_BOOKINGS_REQUEST';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';
export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILURE = 'DELETE_BOOKING_FAILURE';


// FETCH FLIGHTS //
export const FETCH_FLIGHT_BY_ID_REQUEST = 'FETCH_FLIGHT_BY_ID_REQUEST';
export const FETCH_FLIGHT_BY_ID_SUCCESS = 'FETCH_FLIGHT_BY_ID_SUCCESS';
export const FETCH_FLIGHT_BY_ID_FAILURE = 'FETCH_FLIGHT_BY_ID_FAILURE';

// ADMIN ACTION TYPES //
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

// ADMIN FLIGHT ACTION TYPES //
export const SEARCH_FLIGHTS_REQUEST = 'SEARCH_FLIGHTS_REQUEST';
export const SEARCH_FLIGHTS_SUCCESS = 'SEARCH_FLIGHTS_SUCCESS';
export const SEARCH_FLIGHTS_FAILURE = 'SEARCH_FLIGHTS_FAILURE';
export const CREATE_FLIGHT = 'CREATE_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';