// USER ACTION TYPES //
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

// ADMIN ACTION TYPES //
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

// ADMIN FLIGHT ACTION TYPES //
export const SEARCH_FLIGHTS_REQUEST = 'SEARCH_FLIGHTS_REQUEST';
export const SEARCH_FLIGHTS_SUCCESS = 'SEARCH_FLIGHTS_SUCCESS';
export const SEARCH_FLIGHTS_FAILURE = 'SEARCH_FLIGHTS_FAILURE';
export const GET_FLIGHTS = 'GET_FLIGHTS';
export const CREATE_FLIGHT = 'CREATE_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';